app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',                 ['as' => 'home',    'uses' => 'PagesController@home']);
Route::get('about',             ['as' => 'about',   'uses' => 'PagesController@about']);
Route::get('about/contact',     ['as' => 'contact', 'uses' => 'PagesController@contact']);


Route::resource('products', 'ProductsController');

Route::get('cart',              ['as' => 'cart', 'uses' => 'CartController@index']);

Route::post('cart/add',         ['as' => 'cart.add',        'uses' => 'CartController@addProduct']);
Route::post('cart/remove',      ['as' => 'cart.remove',     'uses' => 'CartController@removeProduct']);
Route::post('cart/update',      ['as' => 'cart.update',     'uses' => 'CartController@updateQuantities']);

Route::get('profile',           ['as' => 'profile.edit',    'uses' => 'ProfileController@edit']);
Route::put('profile',           ['as' => 'profile.update',  'uses' => 'ProfileController@update']);

// Authentication routes...
Route::get('auth/login',        ['as' => 'auth.login',      'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login',       ['as' => 'auth.accept',     'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout',       ['as' => 'auth.logout',     'uses' => 'Auth\AuthController@getLogout']);

// Registration routes...
Route::get('auth/register',     ['as' => 'auth.register',   'uses' => 'Auth\AuthController@getRegister']);
Route::post('auth/register',    ['as' => 'auth.store',     'uses' => 'Auth\AuthController@postRegister']);

Route::get('auth/email-available', ['as' => 'auth.email-available', 'uses' => 'Auth\AuthController@getEmailAvailable']);

// Password reset link request routes...
Route::get('password/email',    ['as' => 'password.email',  'uses' => 'Auth\PasswordController@getEmail']);
Route::post('password/email',   ['as' => 'password.send',   'uses' => 'Auth\PasswordController@postEmail']);

// Password reset routes...
Route::get('password/reset/{token}',    ['as' => 'password.reset',  'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset',           ['as' => 'password.accept', 'uses' => 'Auth\PasswordController@postReset']);

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Order;
use App\Product;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class CartController extends Controller

{
    //this ensures users must be logged in to view the cart
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $order = Auth::user()->cart();

        $products = $order->products;

        return view('cart.index', compact('order', 'products'));
    }

    public function addProduct(Request $request) //request gets the info from the post
    {
        $order = Auth::user()->cart(); //gets what the user has in their cart

        $product_id = $request->input('product_id'); //takes productid from form - input gets data from the post (request object)
        $product = Product::findOrFail($product_id); //gets the product form the product id

        $existingProduct = $order->products()->where('product_id', $product->id)->first(); //trys to get the product form the existing order, if exists add 1 to quantity
        if ($existingProduct) {
            $existingProduct->pivot->quantity += 1;
            $existingProduct->pivot->save(); //updates the quantity
        } else { // if the product is not alreay int he order then set the quantity to 1
            $quantity = 1;
            $order->products()->attach($product->id, ['quantity' => $quantity]);
        }
        return redirect()->route('cart');
    }

    public function removeProduct(Request $request)
    {
        $order = Auth::user()->cart();

        $product_id = $request->input('product_id');
        $product = Product::findOrFail($product_id);

        $order->products()->detach($product->id); //removes the product

        return redirect()->route('cart');
    }

    public function updateQuantities(Request $request)
    {
        $quantities = $request->input('quantity');

        $products = [];
        foreach($quantities as $product_id => $quantity) {
            if ($quantity > 0) {
                $products[$product_id] = ['quantity' => $quantity];
            }
        }

        $order = Auth::user()->cart();
        $order->products()->sync($products);

        return redirect()->route('cart');
    }

}

resources/views/cart/index.blade.php
@extends('layouts.master')

@section('content')
  <div class="container">
    <h1>Shopping Cart</h1>
    {!! Form::open(['route' => 'cart.update']) !!}
    <table class="table">
      <thead>
      <tr>
        <th>Product Name</th>
        <th><span class="pull-right">Price</span></th>
        <th><span class="pull-right">Quantity</span></th>
        <th><span class="pull-right">Total</span></th>
      </tr>
      </thead>
      <tbody>
        @forelse($products as $product)
          <tr>
            <td>
              <a href="{{ route('products.show', $product->id) }}">{{ $product->name }}</a>
                {{-- {!! Form::open(['route' => 'cart.remove', 'class' => 'form-inline', 'style' => 'display: inline-block;']) !!}
                  {!! Form::hidden('product_id', $product->id) !!}
                  <button class="btn btn-link text-danger"><span class="glyphicon glyphicon-remove"></span>
                    Remove
                  </button>
                {!! Form::close() !!} --}}

            </td>
            <td><span class="pull-right">{{ number_format($product->price, 2) }}</span></td>
            <td><span class="pull-right">
              {!! Form::number('quantity[' . $product->id . ']', $product->pivot->quantity,
                ['size' => '5', 'class' => 'text-right', 'style' => 'width: 50px']) !!}
            </span></td>
            <td><span class="pull-right">{{ number_format($product->price * $product->pivot->quantity, 2) }}</span></td>
          </tr>
        @empty
          <tr><td colspan="4" class="text-center text-muted">Your cart is empty.</td>
        @endforelse
      </tbody>
    </table>
    <button class="btn btn-primary">Update Quantities</button>
    {!! Form::close() !!}
  </div>
@endsection